name: Docker Image Build and Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "parvgupta123" --password-stdin

      - name: Build Docker Image
        run: docker build -t parvgupta123/fastapi-app:latest .

      - name: Push Docker Image
        run: docker push parvgupta123/fastapi-app:latest
